//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace УП_01._01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReadWriteEntities : DbContext
    {
        public ReadWriteEntities()
            : base("name=ReadWriteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Complaints> Complaints { get; set; }
        public virtual DbSet<Genres> Genres { get; set; }
        public virtual DbSet<ReadingList> ReadingList { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<RoleRequests> RoleRequests { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<UnfreezeRequests> UnfreezeRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
